
export default {
  GET_CURRENT_WEATHER_REQUEST: 'GET_CURRENT_WEATHER_REQUEST',
  SET_CURRENT_WEATHER: 'SET_CURRENT_WEATHER',

  GET_WEATHER_BY_DAYS_REQUEST: 'GET_WEATHER_BY_DAYS_REQUEST',
  SET_WEATHER_BY_DAYS: 'SET_WEATHER_BY_DAYS',
};
